spring.application.name=Shinvia
spring.profiles.active=db,mail,oauth2,client

# Thymeleaf 캐시 비활성화 (HTML/템플릿 수정 시 즉시 반영)
spring.thymeleaf.cache=false

# DevTools 정적 파일(HTML, CSS, JS) 변경 시 서버 재시작 방지 설정
spring.devtools.restart.exclude=static/**,templates/**
